# Generated by Django 2.1.4 on 2018-12-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medImage',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
