# Generated by Django 2.1.4 on 2019-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20190107_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
